name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      - name: Upload to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # ---- IMPORTANT ----
          # In your repo Settings ▸ Secrets and variables ▸ Actions,
          # create a secret named AZURE_STATIC_WEB_APPS_API_TOKEN and paste
          # the Deployment Token you copied from the Azure portal.
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          action: upload

          # Your site lives at the repo root (index.html + staticwebapp.config.json).
          # If you ever move your site into /apps, change app_location to "/apps".
          app_location: "/"

          # No API for this project.
          api_location: ""

          # We're deploying the files as-is (no framework build step).
          output_location: "/"
          skip_app_build: true
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close PR Environment
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
